version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=techshaman.42024769.xyz
      - NGINX_PORT=80
    restart: unless-stopped

  # Alternative: Use http-server with security options
  http-server:
    image: node:18-alpine
    working_dir: /app
    command: >
      sh -c "npm install -g http-server &&
              http-server ./ --port 8080 --no-dotfiles --no-cors --no-cache --no-logs"
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    restart: unless-stopped
