server {
    listen 80;
    server_name _;
    root /app;
    index index.html;

    types {
        application/vnd.apple.mpegurl m3u8;
        video/mp2t ts;
    }

    add_header Access-Control-Allow-Origin "*" always;
    add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Range" always;
    add_header Access-Control-Expose-Headers "Content-Length, Content-Range" always;
    add_header Accept-Ranges bytes always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /wearhaus/ {
        add_header Cache-Control "no-cache" always;
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Range" always;
        add_header Access-Control-Expose-Headers "Content-Length, Content-Range" always;
        if ($request_method = OPTIONS) {
            add_header Content-Length 0;
            add_header Content-Type text/plain;
            return 204;
        }
    }
}
